# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1707.01"

  config.vm.hostname = "base.centos.vbox"
  config.vm.network "private_network", ip: "192.168.16.12"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Vagrant CentOS TDS"
    vb.memory = 8*1024
    vb.cpus = 4
    vb.customize ["storageattach", :id, "--storagectl", "IDE", "--port", 0, "--device", 1, "--type", "dvddrive", "--medium", "emptydrive"]
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
